2020-05-09 22:26:52,300 ERROR: Exception on / [GET] [in c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Lisa\salon\app\routes.py", line 39, in index
    next_url = next_url, prev_url = prev_url)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lisa\salon\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Lisa\salon\app\templates\index.html", line 8, in block "app_content"
    {% include '_master.html' %}
  File "C:\Users\Lisa\salon\app\templates\_master.html", line 6, in top-level template code
    <img src="{{ users[master.user_id|int -1].avatar(110) }}" />
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: list object has no element 6
2020-05-09 22:27:01,910 ERROR: Exception on /index [GET] [in c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Lisa\salon\app\routes.py", line 39, in index
    next_url = next_url, prev_url = prev_url)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lisa\salon\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Lisa\salon\app\templates\index.html", line 8, in block "app_content"
    {% include '_master.html' %}
  File "C:\Users\Lisa\salon\app\templates\_master.html", line 6, in top-level template code
    <img src="{{ users[master.user_id|int -1].avatar(110) }}" />
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: list object has no element 6
2020-05-09 22:41:06,024 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:41:28,442 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:41:59,793 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:42:55,710 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:43:16,768 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:47:30,796 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:52:16,113 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 22:55:51,310 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
2020-05-09 23:02:48,871 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:53]
