2020-05-07 02:07:15,212 ERROR: Exception on / [GET] [in c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Lisa\salon\app\routes.py", line 23, in index
    masters = Master.query.filter(type(user_id) == int).paginate(
NameError: name 'user_id' is not defined
2020-05-07 02:08:33,558 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 02:09:22,255 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 02:11:11,299 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 17:25:08,770 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 17:25:35,266 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 17:25:56,327 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
